name: Makefile CI

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build images
      run: make build-images
  
  tag:
    needs:
      [build]
    runs-on: ubuntu-latest

    steps:
    - name: Tag images
      run: make tag-images
